// 错误代码定义 - 与前端语言包中的 error 对应
export const ErrorCodes = {
    // 认证相关
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
    INVALID_INVITATION_CODE: 'INVALID_INVITATION_CODE',
    INVITATION_CODE_LIMIT: 'INVITATION_CODE_LIMIT',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
    USER_DISABLED: 'USER_DISABLED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    CURRENT_PASSWORD_ERROR: 'CURRENT_PASSWORD_ERROR',
    PASSWORD_LENGTH_ERROR: 'PASSWORD_LENGTH_ERROR',
    EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',  // 账户被锁定（暴力破解防护）
    INVALID_INPUT: 'INVALID_INPUT',  // 无效输入

    // 权限相关
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    NOT_FOUND: 'NOT_FOUND',

    // 操作相关
    SAVE_FAILED: 'SAVE_FAILED',
    DELETE_FAILED: 'DELETE_FAILED',
    UPDATE_FAILED: 'UPDATE_FAILED',
    CREATE_FAILED: 'CREATE_FAILED',
    OPERATION_FAILED: 'OPERATION_FAILED',
    NETWORK_ERROR: 'NETWORK_ERROR',

    // 业务相关
    CONFERENCE_NOT_FOUND: 'CONFERENCE_NOT_FOUND',
    SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
    SEATS_FULL: 'SEATS_FULL',
    VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
    TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
    CREATE_VEHICLE_FAILED: 'CREATE_VEHICLE_FAILED',
    CREATE_TRIP_FAILED: 'CREATE_TRIP_FAILED',
    AREA_NOT_FOUND: 'AREA_NOT_FOUND',
    PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
    HOTEL_NOT_FOUND: 'HOTEL_NOT_FOUND',
    RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
    SEAT_ASSIGNMENT_NOT_FOUND: 'SEAT_ASSIGNMENT_NOT_FOUND',
    MISSING_AREA_ID: 'MISSING_AREA_ID',
    NO_PARTICIPANTS: 'NO_PARTICIPANTS',
    NO_SEAT_AREA: 'NO_SEAT_AREA',
    NO_TABLE: 'NO_TABLE',
    NO_DINING_PARTICIPANTS: 'NO_DINING_PARTICIPANTS',
    TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
    SOURCE_TABLE_NOT_FOUND: 'SOURCE_TABLE_NOT_FOUND',
    TABLE_OCCUPIED: 'TABLE_OCCUPIED',
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    ROOM_FULL: 'ROOM_FULL',
    PARTICIPANT_ALREADY_IN_ROOM: 'PARTICIPANT_ALREADY_IN_ROOM',
    NO_AVAILABLE_ROOM: 'NO_AVAILABLE_ROOM',
    NO_UPDATE_FIELDS: 'NO_UPDATE_FIELDS',
    CANNOT_DELETE_ADMIN: 'CANNOT_DELETE_ADMIN',
    INVITATION_CODE_NOT_FOUND: 'INVITATION_CODE_NOT_FOUND',
    UPLOAD_FILE_REQUIRED: 'UPLOAD_FILE_REQUIRED',
    EMPTY_FILE: 'EMPTY_FILE',
    EXCEL_PARSE_ERROR: 'EXCEL_PARSE_ERROR',
};

/**
 * 返回标准错误响应
 * @param {Hono context} c
 * @param {string} code - 错误代码
 * @param {string} message - 自定义错误消息（可选）
 * @param {number} status - HTTP状态码
 */
export function errorResponse(c, code, message = null, status = 400) {
    const response = { code };
    if (message) {
        response.message = message;
    }
    return c.json(response, status);
}